spring:
  application:
    name: week1
  profiles:
    active: ${APP_PROFILE:dev}
  jpa:
    show_sql: true
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
  sql:
    init:
      mode: never
server:
  port: 8080

app:
  jwt:
    secret: 86168503521dc5a48c4c8959af019c07
    access-token-ttl-minutes: 480
    issuer: yoedu-demo
    refresh-token-ttl-days: 7